import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { ProtectedConfigTampered, repoRoot, sha256 } from "@ct/shared";

/**
 * Files that autonomous agents (Claude) may propose changes to but never
 * modify. Their hashes are pinned in config/PROTECTED.sha256, which is only
 * regenerated by a human via `pnpm verify:protected --update`.
 */
export const PROTECTED_FILES = [
  "validation/locked-periods.json",
  "config/risk-limits.json",
  "config/validation-thresholds.json",
  "config/live-permissions.json",
] as const;

export const PROTECTED_MANIFEST = "config/PROTECTED.sha256";

export interface ProtectedCheck {
  file: string;
  expected: string | null;
  actual: string | null;
  ok: boolean;
}

export function computeProtectedHashes(root = repoRoot()): Record<string, string> {
  const out: Record<string, string> = {};
  for (const f of PROTECTED_FILES) {
    const p = join(root, f);
    if (existsSync(p)) out[f] = sha256(readFileSync(p));
  }
  return out;
}

export function readManifest(root = repoRoot()): Record<string, string> {
  const p = join(root, PROTECTED_MANIFEST);
  if (!existsSync(p)) return {};
  const out: Record<string, string> = {};
  for (const line of readFileSync(p, "utf8").split("\n")) {
    const m = line.trim().match(/^([0-9a-f]{64})\s+(.+)$/);
    if (m) out[m[2] as string] = m[1] as string;
  }
  return out;
}

export function checkProtectedFiles(root = repoRoot()): ProtectedCheck[] {
  const manifest = readManifest(root);
  const actual = computeProtectedHashes(root);
  return PROTECTED_FILES.map((file) => {
    const expected = manifest[file] ?? null;
    const a = actual[file] ?? null;
    return { file, expected, actual: a, ok: expected !== null && expected === a };
  });
}

/** Throws if any protected file differs from its pinned hash. Fail closed. */
export function assertProtectedFilesIntact(root = repoRoot()): void {
  const bad = checkProtectedFiles(root).filter((c) => !c.ok);
  if (bad.length > 0) {
    throw new ProtectedConfigTampered(
      `Protected configuration changed without human re-approval: ${bad.map((b) => b.file).join(", ")}. ` +
        "A human must review the change and run `pnpm verify:protected --update`.",
      { files: bad },
    );
  }
}

/** HUMAN-ONLY: re-pin hashes after reviewing a protected-file change. */
export function writeManifest(root = repoRoot()): string {
  const hashes = computeProtectedHashes(root);
  const body =
    "# Pinned hashes of protected configuration. Regenerate ONLY after human review:\n" +
    "#   pnpm verify:protected --update\n" +
    Object.entries(hashes)
      .map(([f, h]) => `${h}  ${relative(root, join(root, f))}`)
      .join("\n") +
    "\n";
  writeFileSync(join(root, PROTECTED_MANIFEST), body);
  return body;
}
